title: JCR Informática
description: >
  Somos uma empresa de soluções em TI completa e apaixonada 
  pela evolução tecnológica. Formamos uma equipe técnica selecionada 
  e qualificada com muito cuidado e atenção, com o preparo para 
  apresentar sempre as melhores soluções para cuidar da sua empresa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jcrinformatica.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
