title: JCR Informática
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  sections:
    title: Sections
    output: false
  servicos:
    title: Serviços
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
lang: pt_BR
description: >
  Somos uma empresa de soluções em TI completa e apaixonada
  pela evolução tecnológica. Formamos uma equipe técnica selecionada
  e qualificada com muito cuidado e atenção, com o preparo para
  apresentar sempre as melhores soluções para cuidar da sua empresa.
logo: '/img/LogoJCRclaro.png'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jcrinformatica.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed
